export const toggleDropItems = {
  vintage: [
    { category: "Види ги сите" },
    { category: "Панталони" },
    { category: "Здолништа / Шорцеви" },
    { category: "Фустани" },
    { category: "Палта и јакни" },
    { category: "Долна облека" },
  ],
  brands: [
    { id: "0", name: "Види ги сите" },
    { id: "1", name: "Pinc partywear" },
    { id: "2", name: "Factory Girl" },
    { id: "3", name: "Main Days" },
    { id: "4", name: "Нежно" },
    { id: "5", name: "Ред" },
    { id: "6", name: "Наш" },
    { id: "7", name: "Зш да не" },
    { id: "8", name: "Fraeil" },
    { id: "9", name: "Urma" },
    { id: "10", name: "Candle nest" },
    { id: "11", name: "Beyond green" },
    { id: "12", name: "Gatta" },
  ],
  priceRange: [
    { label: "500 - 1000 Ден.", min: 10.99, max: 44.99 },
    { label: "1500 - 2000 Ден.", min: 79, max: 100 },
    { label: "2000 - 2500 ден.", min: 100, max: 130 },
    { label: "Над 80$ Ден", max: 300 },
  ],
  accessories: [
    { accessory: "Види ги сите" },
    { accessory: "Tашни" },
    { accessory: "Накит" },
  ],
  sizes: ["XS", "S", "M", "L", "XL"],
  other: [
    { id: 1, name: "LifeStyle" },
    { id: 2, name: "Подари Картичка*" },
    { id: 3, name: "Попуст" },
  ],
};
